# Docker
- task: Docker@2
  inputs:
    containerRegistry: 'acr'
- task: Docker@2
  inputs:
    containerRegistry: 'acr'
    repository: 'delivery'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: 'azure/*'
    TargetFolder: '$(build.artifactstagingdirectory)'
trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
